### ISSUE TITLE
SECRET_KEY

### ISSUE THREAD

**Issue by nelsonjaviera** [jainskand/Hire-Home-Services#1]
When trying deploy in localhost I get the message 
env\lib\site-packages\django\conf\__init__.py", line 196, in __init__ raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by jainskand** [comment]
open hire_services -> settings.py file 
then replace 
SECRET_KEY = os.environ.get('HIRE_KEY')
with 
SECRET_KEY = 'q=mvwxb95wi7%sv+t*9z(@y&xx8ci#ybfojj=tsygahepzah41'
or with any other random string
